"""first commit

Revision ID: 87cde3a98949
Revises: 
Create Date: 2022-08-02 22:58:06.483410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cde3a98949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carros',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('chassi', sa.String(length=50), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_carros_data_criacao'), 'carros', ['data_criacao'], unique=False)
    op.create_table('condutores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_condutores_data_criacao'), 'condutores', ['data_criacao'], unique=False)
    op.create_table('telefones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('numero', sa.String(length=11), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_telefones_data_criacao'), 'telefones', ['data_criacao'], unique=False)
    op.create_table('tipos_ocorrencias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('tipo_ocorrencia', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_ocorrencia')
    )
    op.create_index(op.f('ix_tipos_ocorrencias_data_criacao'), 'tipos_ocorrencias', ['data_criacao'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('logradouro', sa.String(length=50), nullable=False),
    sa.Column('telefones_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['telefones_id'], ['telefones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_clientes_data_criacao'), 'clientes', ['data_criacao'], unique=False)
    op.create_table('apolices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('valor_franquia', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('clientes_id', sa.BigInteger(), nullable=False),
    sa.Column('carros_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['carros_id'], ['carros.id'], ),
    sa.ForeignKeyConstraint(['clientes_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apolices_condutores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('apolices_id', sa.BigInteger(), nullable=False),
    sa.Column('condutores_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['apolices_id'], ['apolices.id'], ),
    sa.ForeignKeyConstraint(['condutores_id'], ['condutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sinistros',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=False),
    sa.Column('hora_ocorrencia', sa.Time(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('logradouro', sa.String(length=50), nullable=False),
    sa.Column('carros_id', sa.BigInteger(), nullable=False),
    sa.Column('condutores_id', sa.BigInteger(), nullable=False),
    sa.Column('tipos_ocorrencias_id', sa.BigInteger(), nullable=False),
    sa.Column('apolices_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['apolices_id'], ['apolices.id'], ),
    sa.ForeignKeyConstraint(['carros_id'], ['carros.id'], ),
    sa.ForeignKeyConstraint(['condutores_id'], ['condutores.id'], ),
    sa.ForeignKeyConstraint(['tipos_ocorrencias_id'], ['tipos_ocorrencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sinistros')
    op.drop_table('apolices_condutores')
    op.drop_table('apolices')
    op.drop_index(op.f('ix_clientes_data_criacao'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_tipos_ocorrencias_data_criacao'), table_name='tipos_ocorrencias')
    op.drop_table('tipos_ocorrencias')
    op.drop_index(op.f('ix_telefones_data_criacao'), table_name='telefones')
    op.drop_table('telefones')
    op.drop_index(op.f('ix_condutores_data_criacao'), table_name='condutores')
    op.drop_table('condutores')
    op.drop_index(op.f('ix_carros_data_criacao'), table_name='carros')
    op.drop_table('carros')
    # ### end Alembic commands ###
